#ifndef JSMX_CONFIG_H
#define JSMX_CONFIG_H

#ifndef JSMX_WITH_REGEX
#define JSMX_WITH_REGEX 0
#endif

#ifndef JSMX_REGEX_BACKEND_PCRE2
#define JSMX_REGEX_BACKEND_PCRE2 0
#endif

#ifndef JSMX_WITH_CRYPTO
#define JSMX_WITH_CRYPTO 0
#endif

#ifndef JSMX_CRYPTO_BACKEND_OPENSSL
#define JSMX_CRYPTO_BACKEND_OPENSSL 0
#endif

#if JSMX_REGEX_BACKEND_PCRE2 && !JSMX_WITH_REGEX
#error "JSMX_REGEX_BACKEND_PCRE2 requires JSMX_WITH_REGEX=1"
#endif

#if JSMX_CRYPTO_BACKEND_OPENSSL && !JSMX_WITH_CRYPTO
#error "JSMX_CRYPTO_BACKEND_OPENSSL requires JSMX_WITH_CRYPTO=1"
#endif

#endif
